# Generated by Django 3.1.7 on 2021-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('PhoneNum', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('FoodName', models.CharField(choices=[('Vanilla Cake', 'Vanilla Cake'), ('Strawbery Cake', 'Strawbery Cake'), ('Chocolate Cake', 'Chocolate Cake')], max_length=50)),
                ('Payment', models.CharField(choices=[('Bkash(01869537592)', 'Bkash(01869537592)'), ('Rocket(01869537592)', 'Rocket(01869537592)'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('food_Quantity', models.CharField(choices=[('Half pound', 'Half pound'), ('1 pound', '1 pound'), ('2 pound', '2 pound'), ('3 pound', '3 pound'), ('4 pound', '4 pound'), ('5 pound', '5 pound')], max_length=50)),
                ('Textarea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DessertOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('PhoneNum', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('FoodName', models.CharField(choices=[('Nowabi Shemai', 'Nowabi Shemai'), ('Pastry', 'Pastry'), ('Yogurt', 'Yogurt')], max_length=50)),
                ('Payment', models.CharField(choices=[('Bkash(01869537592)', 'Bkash(01869537592)'), ('Rocket(01869537592)', 'Rocket(01869537592)'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('food_Quantity', models.CharField(choices=[('500 ml', '500 ml'), ('1000 ml', '1000 ml'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg')], max_length=50)),
                ('Textarea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpicyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('PhoneNum', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('FoodName', models.CharField(choices=[('Pasta', 'Pasta'), ('Halim', 'Halim'), ('Biryani', 'Biryani')], max_length=50)),
                ('Payment', models.CharField(choices=[('Bkash(01869537592)', 'Bkash(01869537592)'), ('Rocket(01869537592)', 'Rocket(01869537592)'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('food_Quantity', models.CharField(choices=[('500 ml', '500 ml'), ('1000 ml', '1000 ml'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg')], max_length=50)),
                ('Textarea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SweetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('PhoneNum', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('FoodName', models.CharField(choices=[('Khir Mohon', 'Khir Mohon'), ('Sponge Mishti', 'Sponge Mishti'), ('Rashmalay', 'Rashmalay'), ('Pasta', 'Pasta'), ('Halim', 'Halim'), ('Biryani', 'Biryani')], max_length=50)),
                ('Payment', models.CharField(choices=[('Bkash(01869537592)', 'Bkash(01869537592)'), ('Rocket(01869537592)', 'Rocket(01869537592)'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('food_Quantity', models.CharField(choices=[('500 ml', '500 ml'), ('1000 ml', '1000 ml'), ('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg')], max_length=50)),
                ('Textarea', models.TextField()),
            ],
        ),
    ]
